# Generated by Django 4.2.3 on 2023-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tld', models.CharField(max_length=4)),
                ('independent', models.BooleanField()),
                ('UN_member', models.BooleanField()),
                ('currencies', models.CharField(max_length=100)),
                ('idd', models.CharField(max_length=5)),
                ('flag_emoji', models.CharField(max_length=1)),
                ('pop_name', models.CharField(max_length=100)),
                ('languages', models.JSONField()),
                ('maps', models.JSONField()),
                ('populations', models.BigIntegerField()),
                ('car_side', models.CharField(max_length=10)),
                ('timezones', models.CharField(max_length=10)),
                ('continents', models.CharField(max_length=50)),
                ('flag_img_url', models.CharField(max_length=100)),
                ('flag_img_alt', models.TextField()),
                ('coatofarms_img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
