# Generated by Django 4.2.3 on 2023-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodcategory_rename_food_foodrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
